//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registro_de_Pacientes
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pacientes
    {
        public int Id { get; set; }

        [StringLength(14)]
        [Required]
        public string Cedula { get; set; }

        [StringLength(30)]
        [Required]
        public string Nombre { get; set; }

        [StringLength(30)]
        [Required]
        public string Apellido { get; set; }

        [StringLength(3)]
        [Required]
        public string Edad { get; set; }

        [Required]
        [EmailAddress()]
        public string Correo { get; set; }

        [StringLength(50)]
        [Required]
        [Display(Name = "Motivo de Consulta")]
        public string MotivoConsulta { get; set; }

        [StringLength(50)]
        [Required]
        public string Observaciones { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Required]
        public DateTime Fecha { get; set; }
    }
}
